# numpy教程

&ensp;&ensp;NumPy（Numerical Python的简称）是Python科学计算的基础包。它提供以下功能：  
1.快速高效的多维数组对象ndarray。  
2.用于对数组执行元素级计算以及直接对数组执行数学运算的函数。  
3.用于读写硬盘上基于数组的数据集的工具。  
4.线性代数运算、傅里叶变换以及随机数生成。  

## numpy矩阵和数组的区别

NumPy函数库中存在两种不同的数据类型（矩阵matrix和数组array），虽然它们很相似，但是执行相同的数学运算可能得到不同的结果。

In [1]:
#数组
import numpy as np
np.random.rand(4,4)

array([[0.00687137, 0.70330468, 0.20813727, 0.58129288],
       [0.64796542, 0.85035907, 0.28790362, 0.13788007],
       [0.09214624, 0.5744963 , 0.50535701, 0.89935095],
       [0.66125405, 0.850663  , 0.25309954, 0.7324152 ]])

In [2]:
#矩阵
randMat=np.mat(np.random.rand(4,4))  #调用mat()函数可以将数组转化为矩阵
#.I操作符实现了矩阵求逆的运算
randMat.I

matrix([[ 83.93984274, -43.3654061 , -23.43214965,  -8.69993158],
        [-23.73101426,  12.1595981 ,   5.27362283,   6.74862705],
        [-52.19484808,  28.49460248,  14.67115409,   3.41597509],
        [ 17.76753726, -10.04695963,  -2.74070474,  -4.35284874]])

In [3]:
#矩阵的乘法
invRandMat=randMat.I
randMat*invRandMat
#结果应该是单位矩阵，除了对角线是1，其余元素都是0，实际结果略有不同，留下了许多非常小的元素，这是计算机处理的误差结果

matrix([[ 1.00000000e+00,  8.88178420e-16,  4.44089210e-16,
          0.00000000e+00],
        [ 1.77635684e-15,  1.00000000e+00,  1.77635684e-15,
          0.00000000e+00],
        [ 2.22044605e-15,  2.88657986e-15,  1.00000000e+00,
          4.44089210e-16],
        [ 8.88178420e-16, -4.44089210e-16,  6.66133815e-16,
          1.00000000e+00]])

In [4]:
#单位矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 1.创建数组

NumPy最重要的一个特点就是其N维数组对象（即ndarray），该对象是一个快速而灵活的大数据集容器。  
ndarray是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的。  
常用函数:  
(1)shape（一个表示各维度大小的元组,如果是2维的话，shape[0]表示行，shape[1]表示列）==>(1,2)表示1行2列;  
(2)dtype（一个用于说明数组数据类型的对象）;  
(3)size(展示的是数组a的规模，就是a的元素个数为多少);  
(4)ndim(就是数组a有几个维度，比如3就代表数组a有三个维度);  
(5)arange(是Python内置函数range的数组版,类似内置的range，但返回的是一个ndarray而不是列表);

###  1.1 使用np.array()直接创建

In [5]:
np.array([1,2,3])

array([1, 2, 3])

### 1.2 使用 np.ones()、np.zeros() 等方法 

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.random.randn(2,3)

array([[-1.60898476,  0.33710152,  1.0617532 ],
       [-1.16154912, -0.41046716, -1.47526273]])

## 2.数组运算

### 2.1 加减运算

In [9]:
data=np.array([1,2])
ones=np.ones(2)
print(data+ones)
print(data-ones)

[2. 3.]
[0. 1.]


### 2.2 数组乘以数值

In [10]:
data*2

array([2, 4])

### 2.3 数组索引

In [11]:
#只取一个
data[0]

1

In [12]:
#取子串
data[0:2]

array([1, 2])

### 2.4 数组聚合

In [13]:
print(data.max())
print(data.min())
print(data.sum())

2
1
3


## 3.矩阵

### 3.1 创建矩阵

In [14]:
#直接创建
print(np.array([[1,2],[3,4]]))
#使用 np.ones()、np.zeros() 等方法
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.98627283 0.17182198]
 [0.46271515 0.82566967]
 [0.68514157 0.5003767 ]]


### 3.2 矩阵运算

In [15]:
data=np.array([[1,2],[3,4]])
ones=np.ones((2,2))
print(data+ones)

ones_row=np.ones(2)
print(data+ones_row)

[[2. 3.]
 [4. 5.]]
[[2. 3.]
 [4. 5.]]


### 3.3 矩阵点积 

In [16]:
data.dot(ones)

array([[3., 3.],
       [7., 7.]])

In [17]:
np.dot(data,ones)

array([[3., 3.],
       [7., 7.]])

### 3.4 矩阵索引 

In [18]:
data

array([[1, 2],
       [3, 4]])

In [19]:
print(data[0,1])
#取行
print(data[0,0:])

2
[1 2]


In [20]:
#取列
data[0:,0]

array([1, 3])

### 3.5 矩阵聚合

In [21]:
#求最值
print(data.max())
print(data.min())
print(data.sum())


4
1
10


In [22]:
#按行聚合
data.max(axis=0)

array([3, 4])

In [23]:
#按列聚合
data.max(axis=1)

array([2, 4])

### 3.6 矩阵转置

In [24]:
data.T

array([[1, 3],
       [2, 4]])

### 3.7 矩阵重塑

In [25]:
data=np.array([1,2,3,4,5,6])
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## 4.通用函数

通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。

### 4.1 一元ufunc函数说明  
    abs、fabs：计算整数、浮点数或复数的绝对值。对于非复数值，可以使用更快的fabs；  
    sqrt：计算各元素的平方根。相当于arr** 0.5；  
    square：计算各元素的平方。相当于arr** 2；  
    exp：计算各元素的指数ex；  
    log、log10、 log2、 log1p：分别为自然对数(底数为e)、底数为10的log、底数为2的log、log(1 + x)；  
    sign：计算各元素的正负号: 1 (正数)、0 (零)、-1 (负数)；  
    ceil：计算各元素的ceiling值，即大于等于该值的最小整数；  
    floor：计算各元素的floor值，即小于等于该值的最大整数；  
    rint：将各元素值四舍五入到最接近的整数，保留dtype；  
    modf：将数组的小数和整数部分以两个独立数组的形式返回；  
    isnan：返回一个表示“哪些值是NaN (这不是一个数字)”的布尔型数组；  
    isfinite、isinf：分别返回一个表示“哪些元素是有穷的(非inf，非NaN)”或“哪些元素是无穷的”的布尔型数组；  
    cos、cosh、 sin、 sinh、tan、tanh：普通型和双曲型三角函数；  
    arccos、arccosh、 arcsin、arcsinh、arctan、 arctanh：反三角函数；  
    logical_ not：计算各元素notx的真值。相当于-arr；
   

### 4.2 二 元ufunc函数说明
    add：将数组中对应的元素相加；   
    subtract：从第一个数组中减去第二个数组中的元素；    
    multiply：数组元素相乘；  
    divide. floor_ _divide：除法或向下圆整除法(丢弃余数)；  
    power：对第一个数组中的元素A，根据第二个数组中的相应元素B，计算A；  
    maximum、fmax：元素级的最大值计算。fmax 将忽略NaN；  
    minimum、fmin：元素级的最小值计算。fmin将忽略NaN；  
    mod：元素级的求模计算(除法的余数)；  
    copysign：将第二个数组中的值的符号复制给第一个数组中的值；  
    greater、greater_ equal、less、less_ equal、equal、not_ equal：执行元素级的比较运算，最终产生布尔型数组。相当于中缀运算符>、>=、<. <=. ==、!=  
    logical_ and、 logical _or、logical xor：执行元素级的真值逻辑运算。相当于中缀运算符&、| ^  


## 5.线性代数

常用函数： 

    (1)diag:以一维数组的形式返回方阵的对角线(或非对角线)元素，或将一维数组转换为方阵(非对角线元素为0)；  
    (2)dot:矩阵点乘；  
    (3)trace：计算对角线元素的和；  
    (4)det：计算矩阵行列式；  
    (5)eig:计算方阵的特征值和特征向量；  
    (6)inv:计算方阵的逆；  
    (7)pinv:计算矩阵的Moore-Penrose伪逆；  
    (8)qr:计算QR分解；  
    (9)svd:计算奇异值分解(SVD)；  
    (10)solve:解线性方程组Ax=b，其中A为一个方阵；  
    (11)lstsq:计算Ax=b的最小二乘解；  

## 6.数学和统计方法

可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算。

    (1)sum:对数组中全部或某轴向的元素求和。零长度的数组的sum为0；【arr.sum(1)是计算每行的和；arr.sum(0)是计算每列的和】
    (2)mean：算术平均值，零长度的数组的mean为NaN；
    (3)std、var:分别为标准差和方差，自由度可调(默认为n)；
    (4)min、max:最小值和最大值；
    (5)argmin、argmax:分别为最小值和最大值的索引；
    (6)cumsum:所有元素的累计和；
    (7)cumprod:所有元素的累计积；