# numpy教程

## 1.创建数组

###  1.1 使用np.array()直接创建

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

### 1.2 使用 np.ones()、np.zeros() 等方法 

In [2]:
np.ones(3)

array([1., 1., 1.])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.random.random(3)

array([0.25395684, 0.48852922, 0.41314586])

## 2.数组运算

### 2.1 加减运算

In [5]:
data=np.array([1,2])
ones=np.ones(2)
print(data+ones)
print(data-ones)

[2. 3.]
[0. 1.]


### 2.2 数组乘以数值

In [6]:
data*2

array([2, 4])

### 2.3 数组索引

In [22]:
#只取一个
data[0]

1

In [23]:
#取子串
data[0:2]

array([1, 2])

### 2.4 数组聚合

In [7]:
print(data.max())
print(data.min())
print(data.sum())

2
1
3


## 3.矩阵

### 3.1 创建矩阵

In [8]:
#直接创建
print(np.array([[1,2],[3,4]]))
#使用 np.ones()、np.zeros() 等方法
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.87339038 0.75223909]
 [0.36166049 0.17653184]
 [0.05606722 0.81977247]]


### 3.2 矩阵运算

In [24]:
data=np.array([[1,2],[3,4]])
ones=np.ones((2,2))
print(data+ones)

ones_row=np.ones(2)
print(data+ones_row)

[[2. 3.]
 [4. 5.]]
[[2. 3.]
 [4. 5.]]


### 3.3 矩阵点积 

In [10]:
data.dot(ones)

array([[3., 3.],
       [7., 7.]])

### 3.4 矩阵索引 

In [28]:
print(data[0,1])
#取行
print(data[1,0:])

2
[3 4]


In [26]:
#取列
data[0:,0]

array([1, 3])

### 3.5 矩阵聚合

In [13]:
#求最值
print(data.max())
print(data.min())
print(data.sum())


4
1
10


In [14]:
#按行聚合
data.max(axis=0)

array([3, 4])

In [15]:
#按列聚合
data.max(axis=1)

array([2, 4])

### 3.6 矩阵转置

In [16]:
data.T

array([[1, 3],
       [2, 4]])

### 3.7 矩阵重塑

In [17]:
data=np.array([1,2,3,4,5,6])
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])